config/routes.rb
Messaging::Application.routes.draw do
  root to: 'home#show'

  devise_for :users
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_messageable

  # You'd, probably, want to have a separate name column instead
  def name
    email
  end

  def mailboxer_email(object)
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  helper_method :mailbox, :conversation

  def create
    recipient_emails = conversation_params(:recipients).split(',')
    recipients = User.where(email: recipient_emails).all

    conversation = current_user.
      send_message(recipients, *conversation_params(:body, :subject)).conversation

    redirect_to conversation_path(conversation)
  end

  def reply
    current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to :conversations
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to :conversations
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
      when 0 then self
      when 1 then self[subkeys.first]
      else subkeys.map{|k| self[k] }
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice
    flash[:notice]
  end

  def alert
    flash[:alert]
  end
end

app/views/conversations/_conversation.html.haml
= content_tag_for(:li, conversation) do |conversation|
  %p
    = link_to conversation.subject, conversation_path(conversation)
    |
    - if conversation.is_completely_trashed?(current_user)
      = link_to 'Untrash', untrash_conversation_path(conversation), method: :post
    - else
      = link_to 'Move to trash', trash_conversation_path(conversation), method: :post

app/views/conversations/_form.html.haml
= simple_form_for :conversation, url: :conversations do |f|
  = f.input :recipients
  = f.input :subject
  = f.input :body, as: :text
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = f.button :submit, 'Cancel', type: :reset, class: 'btn-danger'

app/views/conversations/index.html.haml
%h1 Conversations
%h2 Inbox
%ul= render collection: mailbox.inbox, partial: 'conversation'
%h2 Sentbox
%ul= render collection: mailbox.sentbox, partial: 'conversation'
%h2 Trash
%ul= render collection: mailbox.trash, partial: 'conversation'

= link_to 'Start Conversation', :new_conversation

app/views/conversations/new.html.haml
%h1 Start Conversation
= render 'form'

app/views/conversations/show.html.haml
%h1= conversation.subject
%ul
  = content_tag_for(:li, conversation.receipts_for(current_user)) do |receipt|
    - message = receipt.message
    %h3= message.subject
    %p= message.body
= render 'messages/form', conversation: conversation

app/views/home/show.html.erb
<h1>Hello</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messaging</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>
  <% if signed_in? %>
    <p>Signed in as <%= current_user.email %> (<%= link_to 'sign out', :destroy_user_session, method: :delete %>)</p>
    <p><%= link_to 'My Conversations', :conversations %></p>
  <% else %>
    <p>Please, <%= link_to 'sign in', :new_user_session %></p>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/messages/_form.html.haml
= simple_form_for :message, url: reply_conversation_path(conversation) do |f|
  = f.input :subject
  = f.input :body
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = submit_tag 'Cancel', type: :reset, class: 'btn btn-danger'